### PR TITLE
Create a known_hosts file with an update script

### PR DESCRIPTION
**Pull request by pjcdawkins**
Alternative to #1 

Uses the CLI (for authentication and configuration) to fetch the regions list.

Commits the list to Git, so that it's clear when host keys change.

### CODE REVIEW

**Comment by hussainweb** [comment]
Like I said in #1, I started maintaining a Docker image for my organization with these changes. I kept adding domains as I encountered them and I think you got them all. You can see my list here: https://github.com/axelerant/docker-platformsh-cli/blob/master/Dockerfile

**Comment by pjcdawkins** [comment]
@hussainweb it looks like I'm missing `eu.platform.sh`, probably because it's so old that it's become a "private" region for our API, I'll ask what we can do about that

**Comment by arnested** [comment]
@pjcdawkins `eu-4` is also missing.

In the project overview in the UI console, projects on `eu` and `eu-4` doesn't display their region either. Guess it's the same root cause.

**Comment by hussainweb** [comment]
Thanks for merging this! I can now begin deprecating [our image](https://hub.docker.com/repository/docker/axelerant/platformsh-cli) and just use this directly.

**Pull request merged**
